### PR TITLE
optimize to reduce allocations (also for speed)

### PR DESCRIPTION
**Pull request by omsmith**
Hey there

Came across a co-worker using this library while investigating some excess memory usage. While this wasn't necessarily the culprit, after having a look, it certainly wasn't being as lean as it could be.

I've done some refactoring, mainly to reduce the number of closures being created (as very few are necessary). While doing so, I also removed the usage of `bind` to avoid that performance hit.

The pie charts below are heapdumps from running the same simple test[1]. Left to right is before and after the test run, where the top row is with the patch applied, and the bottom row is with master:
image
_EDIT: Pushed an update that uses just `then` instead of `then/catch` which drops these numbers a miniscule amount_

As well, running a simple benchmark[2] to compare overall time working, we find we end up being "quite a bit faster":

```
Scores: (bigger is better)

optimized
Raw:
 > 3.032967032967033
 > 3.101898101898102
 > 3.078921078921079
 > 2.901098901098901
Average (mean) 3.028721278721279

master
Raw:
 > 0.9181636726546906
 > 0.9200799200799201
 > 0.908183632734531
 > 0.8971028971028971
Average (mean) 0.9108825306430097

Winner: optimized
Compared with next highest (master), it's:
69.93% faster
3.33 times as fast
0.52 order(s) of magnitude faster
QUITE A BIT FASTER
```

Anyway, hope you find this patch useful. Happy to resolve any stylistic differences or whatnot.

``` js
// [1]: allocations.js
'use strict';

const heapdump = require('heapdump');
const settle = require('../node-promise-settle');

heapdump.writeSnapshot();

const N = 1000;
const M = 50;

const all = new Array(N);

for (let n = 0; n < N; ++n) {
    const p = new Array(M).fill(Promise.resolve());

    all[n] = settle(p);
}

Promise
    .all(all)
    .then(() => heapdump.writeSnapshot());
```

``` js
// [2]: bench.js
'use strict';

const master = require('../node-promise-settle-orig');
const optimized = require('../node-promise-settle');

const M = 100;

module.exports.compare = {
    master: function (done) {
        const p = new Array(M).fill(Promise.resolve());
        master(p).then(done);
    },
    optimized: function (done) {
        const p = new Array(M).fill(Promise.resolve());
        optimized(p).then(done);
    }
};

require('bench').runMain();
```

### CODE REVIEW

**Comment by vitaly-t** [comment]
I wonder how this will compare to the performance of [spex.batch](https://github.com/vitaly-t/spex/blob/master/docs/code/batch.md) now... need some testing :)

**Comment by pgaubatz** [comment]
Hey @omsmith!

Thanks for this PR! Great work indeed.
One minor "issue": could you update your PR to use 2 spaces for indentation instead of tabs?
Other than that I'd be happy to merge your changes.

Cheers,
Patrick

**Comment by omsmith** [comment]
Ha yep, no problem. Pushed that up.

**Comment by pgaubatz** [comment]
Merged. Thanks!

**Pull request merged**
